baseURL = 'https://erickkariuki98.github.io/blog/'
languageCode = 'en-us'
title = 'Erick KariukI Blog'
theme = 'm10c'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[params]
author = 'Erickkariuki'
avatar = 'karis.png'
description = 'Erick Kariuki. A Developer from Nairobi'

[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/Erickkariuki98"

[[params.social]]
icon = "website"
name = "Linktree"
url = "https://erickkariuki98.github.io/"

