baseURL = 'Erickkariuki98.pages.dev/'
languageCode = 'en-us'
title = 'This is my personal blog. Sharing is caring'
theme = 'm10c'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "https://Erickkariuki98.github.io/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[params]
author = 'Erickkariuki'
avatar = 'avatar_ignytis.jpg'
description = 'My name is Erick Kariuki and welcome to my blog!'
[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/Erickkariuki98"

[[params.social]]
icon = "website"
name = "Linktree"
url = "https://linktr.ee/i"

