baseURL = 'https://Erickkariuki98.github.io/'
languageCode = 'en-us'
title = 'A personal blog. Sharing is caring'
theme = 'm10c'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[params]
author = 'Erickkariuki'
avatar = 'avatar_ignytis.jpg'
description = 'Erick Kariuki. A Software Engineer from Nairobi'

[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/Erickkariuki98"

[[params.social]]
icon = "website"
name = "Linktree"
url = "https://linktr.ee/igny"

